export const environment = {
  production: true,
  ansokanDjurvalfardUrl: '/farmen/aredat/ansokandjurvalfard',
  ansokansTyperUrl: '/farmen/grund/ansokanstyper',
  antalArendenUrl: '/farmen/arende/antaltotalt',
  arendenUrl: '/farmen/arende/arenden',
  arendeTyperUrl: '/farmen/arende/arendetyper',
  arendeVersionerUrl: '/farmen/arende/arendeversioner',
  arendeVersionIdUrl: '/farmen/arende/aktuellarendeversion',
  atgarderUrl: '/farmen/atg/atgarder',
  atgardTyperUrl: '/farmen/atg/manuellaatgardtyper',
  attributUrl: '/farmen/arende/attribut',
  beslutInfoUrl: '/farmen/arende/beslutsinformation',
  giltigaAttributUrl: '/farmen/arende/giltigaattribut',
  masshanteringUrl: '/farmen/arende/masshantering',
  myndigheterUrl: '/farmen/intr/myndigheter',
  paverkadeArendenUrl: '/farmen/arende/antalpaverkade',
  skapaAttributUrl: '/farmen/arende/skapaattribut',
  skapaManuellAtgardUrl: '/farmen/atg/skapaatgard',
  redigeraAtgardUrl: '/farmen/atg/redigeraatgard',
  redigeraAttributUrl: '/farmen/arende/redigeraattribut',
  stodArUrl: '/farmen/intr/stodar',
  statusUrl: '/farmen/grund/arendestatusar',
  taBortAttributUrl: '/farmen/arende/tabortattribut',
  redigeraAnsokanUrl: '/farmen/aredat/redigeraansokan'
};
